let segmenterPromise=null, segmenter=null;
const MP_CDN='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/vision_bundle.mjs';
const WASM_ROOT='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm';
const MODEL_URL='https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite';
async function loadPortraitAI(){if(segmenter)return;if(!segmenterPromise){segmenterPromise=(async()=>{const vision=await import(MP_CDN);const {FilesetResolver,ImageSegmenter}=vision;const fileset=await FilesetResolver.forVisionTasks(WASM_ROOT);try{segmenter=await ImageSegmenter.createFromOptions(fileset,{baseOptions:{modelAssetPath:MODEL_URL,delegate:'GPU'},runningMode:'IMAGE',outputCategoryMask:true,outputConfidenceMasks:false})}catch(e){console.warn('GPU failed, retrying CPU',e);segmenter=await ImageSegmenter.createFromOptions(fileset,{baseOptions:{modelAssetPath:MODEL_URL,delegate:'CPU'},runningMode:'IMAGE',outputCategoryMask:true,outputConfidenceMasks:false})}return segmenter})()}await segmenterPromise}
function getMask(sourceCanvas){if(!segmenter)throw Error('Portrait AI is not loaded.');const result=segmenter.segment(sourceCanvas);if(!result.categoryMask)throw Error('Segmentation mask was not returned.');const mask=result.categoryMask,w=mask.width,h=mask.height,values=mask.getAsUint8Array(),out=document.createElement('canvas');out.width=w;out.height=h;const x=out.getContext('2d'),im=x.createImageData(w,h);for(let i=0,p=0;i<values.length;i++,p+=4){const a=values[i]>0?255:0;im.data[p]=255;im.data[p+1]=255;im.data[p+2]=255;im.data[p+3]=a}x.putImageData(im,0,0);return out}
function blurCanvas(source,r){const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const x=c.getContext('2d');x.filter=`blur(${r}px)`;x.drawImage(source,0,0);return c}
function refinedMask(mask,edgeProtection){const c=document.createElement('canvas');c.width=mask.width;c.height=mask.height;const x=c.getContext('2d');const feather=Math.max(1,Math.round(6-(edgeProtection/100)*5));x.filter=`blur(${feather}px)`;x.drawImage(mask,0,0);x.filter='none';return c}
async function applyPortraitAI(sourceCanvas,depthPercent,edgeProtection,progress){progress('Running person segmentation…');const raw=getMask(sourceCanvas);progress('Refining subject edge…');const mask=refinedMask(raw,edgeProtection);progress('Building depth-style background blur…');const blurRadius=1+depthPercent*.13,blurred=blurCanvas(sourceCanvas,blurRadius),out=document.createElement('canvas');out.width=sourceCanvas.width;out.height=sourceCanvas.height;const o=out.getContext('2d');o.drawImage(blurred,0,0);const subject=document.createElement('canvas');subject.width=out.width;subject.height=out.height;const s=subject.getContext('2d');s.drawImage(sourceCanvas,0,0);s.globalCompositeOperation='destination-in';s.drawImage(mask,0,0);o.drawImage(subject,0,0);return out}
export {loadPortraitAI,applyPortraitAI};
