import { loadPortraitAI, applyPortraitAI } from './portrait-model.js';
(() => {
  const file=document.getElementById('portraitFile'), canvas=document.getElementById('portraitCanvas'), ctx=canvas.getContext('2d',{willReadFrequently:true});
  const status=document.getElementById('portraitStatus'), loadAI=document.getElementById('loadPortraitAI'), apply=document.getElementById('applyPortrait'), download=document.getElementById('downloadPortrait');
  const depth=document.getElementById('depth'), edge=document.getElementById('edge'), depthValue=document.getElementById('depthValue'), edgeValue=document.getElementById('edgeValue');
  let sourceCanvas=null, finalCanvas=null, aiReady=false;
  const setStatus=t=>status.textContent=t;
  depth.addEventListener('input',()=>depthValue.textContent=depth.value+'%');
  edge.addEventListener('input',()=>{const v=+edge.value;edgeValue.textContent=v>=75?'High':v>=40?'Medium':'Low'});
  file.addEventListener('change',async e=>{const selected=e.target.files?.[0];if(!selected)return;try{setStatus('Opening photo…');const url=URL.createObjectURL(selected),img=new Image();img.decoding='async';await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});URL.revokeObjectURL(url);const max=1800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));sourceCanvas=document.createElement('canvas');sourceCanvas.width=Math.max(1,Math.round(img.naturalWidth*scale));sourceCanvas.height=Math.max(1,Math.round(img.naturalHeight*scale));sourceCanvas.getContext('2d').drawImage(img,0,0,sourceCanvas.width,sourceCanvas.height);canvas.width=sourceCanvas.width;canvas.height=sourceCanvas.height;ctx.drawImage(sourceCanvas,0,0);aiReady=false;finalCanvas=null;loadAI.disabled=false;apply.disabled=true;download.disabled=true;setStatus(`PHOTO LOADED ✓  ${img.naturalWidth} × ${img.naturalHeight}`)}catch(err){console.error(err);setStatus('Could not decode this image.')}});
  loadAI.addEventListener('click',async()=>{if(!sourceCanvas)return;loadAI.disabled=true;setStatus('Loading Portrait AI…');try{await loadPortraitAI();aiReady=true;apply.disabled=false;setStatus('PORTRAIT AI READY ✓')}catch(err){console.error(err);loadAI.disabled=false;setStatus('AI could not load. Check internet/CDN access.')}});
  apply.addEventListener('click',async()=>{if(!sourceCanvas||!aiReady)return;apply.disabled=true;setStatus('Detecting person and creating depth blur…');try{finalCanvas=await applyPortraitAI(sourceCanvas,+depth.value,+edge.value,setStatus);canvas.width=finalCanvas.width;canvas.height=finalCanvas.height;ctx.drawImage(finalCanvas,0,0);download.disabled=false;apply.disabled=false;setStatus('PORTRAIT EFFECT APPLIED ✓')}catch(err){console.error(err);apply.disabled=false;setStatus('Portrait processing failed. Open browser console for details.')}});
  download.addEventListener('click',()=>{if(!finalCanvas)return;finalCanvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.download='portrait-mode.jpg';a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',.94)});
})();
