let segmenter=null,loading=null;
const MODEL='https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite';
const CDNS=['https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/vision_bundle.mjs','https://unpkg.com/@mediapipe/tasks-vision@1.0.1/vision_bundle.mjs'];
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm';
export async function loadPortraitAI(report){if(segmenter)return;if(loading)return loading;loading=(async()=>{let vision=null,last=null;for(const url of CDNS){try{report('Loading MediaPipe runtime…',null,url);vision=await import(url);report('MediaPipe runtime loaded ✓',true);break}catch(e){last=e;report('Runtime attempt failed',false,e.message||String(e))}}if(!vision)throw last||new Error('No runtime CDN could be loaded');const {FilesetResolver,ImageSegmenter}=vision;report('Loading MediaPipe WASM…',null,WASM);const fs=await FilesetResolver.forVisionTasks(WASM);report('MediaPipe WASM loaded ✓',true);
report('Loading person segmentation model…',null,MODEL);const response=await fetch(MODEL,{mode:'cors',cache:'force-cache'});if(!response.ok)throw new Error(`Model HTTP ${response.status}`);report('Segmentation model reachable ✓',true,`${Math.round((+response.headers.get('content-length')||0)/1024)} KB reported`);
try{report('Initializing CPU ImageSegmenter…');segmenter=await ImageSegmenter.createFromModelPath(fs,MODEL);report('CPU ImageSegmenter ready ✓',true)}catch(cpuErr){report('CPU ImageSegmenter failed',false,cpuErr.message||String(cpuErr));report('Trying GPU ImageSegmenter…');segmenter=await ImageSegmenter.createFromOptions(fs,{baseOptions:{modelAssetPath:MODEL,delegate:'GPU'},runningMode:'IMAGE',outputCategoryMask:true,outputConfidenceMasks:false});report('GPU ImageSegmenter ready ✓',true)}return segmenter})();try{return await loading}catch(e){loading=null;throw e}}
function makeMask(source){const r=segmenter.segment(source);if(!r.categoryMask)throw Error('No category mask returned');const m=r.categoryMask,v=m.getAsUint8Array(),c=document.createElement('canvas');c.width=m.width;c.height=m.height;const x=c.getContext('2d'),im=x.createImageData(m.width,m.height);for(let i=0,p=0;i<v.length;i++,p+=4){const a=v[i]>0?255:0;im.data[p]=255;im.data[p+1]=255;im.data[p+2]=255;im.data[p+3]=a}x.putImageData(im,0,0);return c}
function blur(s,r){const c=document.createElement('canvas');c.width=s.width;c.height=s.height;const x=c.getContext('2d');x.filter=`blur(${r}px)`;x.drawImage(s,0,0);x.filter='none';return c}function soft(m,e){const c=document.createElement('canvas');c.width=m.width;c.height=m.height;const x=c.getContext('2d');x.filter=`blur(${Math.max(.6,(100-e)*.04+.6)}px)`;x.drawImage(m,0,0);x.filter='none';return c}
export async function applyPortraitAI(source,depth,edge,progress){progress('Running person segmentation…');const raw=makeMask(source);progress('Refining subject edge…');const mask=soft(raw,edge);progress('Creating background blur…');const bg=blur(source,1+depth*.14);const out=document.createElement('canvas');out.width=source.width;out.height=source.height;const o=out.getContext('2d');o.drawImage(bg,0,0);const subject=document.createElement('canvas');subject.width=source.width;subject.height=source.height;const s=subject.getContext('2d');s.drawImage(source,0,0);s.globalCompositeOperation='destination-in';s.drawImage(mask,0,0,source.width,source.height);o.drawImage(subject,0,0);return {canvas:out,mask}}
