import { loadPortraitAI, applyPortraitAI } from './portrait-model.js';
const $=id=>document.getElementById(id); const file=$('portraitFile'),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}); const status=$('status'),load=$('load'),apply=$('apply'),download=$('download'),depth=$('depth'),edge=$('edge'),showMask=$('showMask'),diag=$('diag'); let source=null,result=null,mask=null;
function st(t){status.textContent=t} function log(t,ok=null){const li=document.createElement('li');li.textContent=t;if(ok!==null)li.className=ok?'ok':'fail';diag.appendChild(li)} function clearLog(){diag.innerHTML=''}
depth.oninput=()=>{};edge.oninput=()=>{};
file.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;clearLog();log('Photo selected.');try{st('Opening photo…');const u=URL.createObjectURL(f),img=new Image();img.decoding='async';await new Promise((r,j)=>{img.onload=r;img.onerror=j;img.src=u});URL.revokeObjectURL(u);const scale=Math.min(1,1800/Math.max(img.naturalWidth,img.naturalHeight));source=document.createElement('canvas');source.width=Math.round(img.naturalWidth*scale);source.height=Math.round(img.naturalHeight*scale);source.getContext('2d').drawImage(img,0,0,source.width,source.height);canvas.width=source.width;canvas.height=source.height;ctx.drawImage(source,0,0);load.disabled=false;apply.disabled=true;download.disabled=true;st(`PHOTO LOADED ✓ ${img.naturalWidth} × ${img.naturalHeight}`);log(`Preview pipeline OK (${source.width} × ${source.height}).`,true)}catch(e){console.error(e);log('Image decode failed.',false);st('Could not decode this image.')}};
load.onclick=async()=>{if(!source)return;load.disabled=true;clearLog();log('Starting AI diagnostics…');try{await loadPortraitAI((stage,ok,detail)=>{log(`${stage}${detail?' — '+detail:''}`,ok);st(stage)});apply.disabled=false;st('PORTRAIT AI READY ✓');log('Portrait AI initialization complete.',true)}catch(e){console.error(e);load.disabled=false;st('AI load failed. Read diagnostics below.');if(!diag.lastChild?.textContent.includes('FAILED'))log('FAILED — '+(e?.message||String(e)),false)}};
apply.onclick=async()=>{if(!source)return;apply.disabled=true;showMask.checked=false;try{const r=await applyPortraitAI(source,+depth.value,+edge.value,m=>st(m));result=r.canvas;mask=r.mask;canvas.width=result.width;canvas.height=result.height;ctx.drawImage(result,0,0);download.disabled=false;st('PORTRAIT EFFECT APPLIED ✓')}catch(e){console.error(e);st('Portrait processing failed. See diagnostics.');log('Processing failed — '+(e?.message||String(e)),false)}finally{apply.disabled=false}};
showMask.onchange=()=>{if(!source||!mask)return;if(!showMask.checked){ctx.drawImage(result||source,0,0);return}ctx.drawImage(source,0,0);const o=document.createElement('canvas');o.width=canvas.width;o.height=canvas.height;const x=o.getContext('2d');x.drawImage(mask,0,0,o.width,o.height);const d=x.getImageData(0,0,o.width,o.height);for(let i=0;i<d.data.length;i+=4){const a=d.data[i+3];d.data[i]=40;d.data[i+1]=220;d.data[i+2]=100;d.data[i+3]=Math.round(a*.35)}x.putImageData(d,0,0);ctx.drawImage(o,0,0)};
download.onclick=()=>{if(!result)return;result.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='portrait-mode.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',.94)};
