import { FilesetResolver, ImageSegmenter } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/vision_bundle.mjs";
const $=id=>document.getElementById(id), fileInput=$("fileInput"), preview=$("preview"), pctx=preview.getContext("2d",{willReadFrequently:true}), status=$("status"), processBtn=$("process"), downloadBtn=$("download"), depth=$("depth"), edge=$("edge"), preset=$("preset"), showMask=$("showMask");
const MULTI_MODEL="https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_multiclass_256x256/float32/latest/selfie_multiclass_256x256.tflite";
const HAIR_MODEL="https://storage.googleapis.com/mediapipe-models/image_segmenter/hair_segmenter/float32/latest/hair_segmenter.tflite";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm";
let image=null,working=null,finalCanvas=null,multiSegmenter=null,hairSegmenter=null,multiMask=null,busy=false;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;function setStatus(t){status.textContent=t}
async function initModels(){setStatus("Loading local portrait model…");const vision=await FilesetResolver.forVisionTasks(WASM);multiSegmenter=await ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:MULTI_MODEL},runningMode:"IMAGE",outputCategoryMask:true,outputConfidenceMasks:true});hairSegmenter=await ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:HAIR_MODEL},runningMode:"IMAGE",outputCategoryMask:true,outputConfidenceMasks:true});setStatus("Portrait model ready.")}
function makeWorkingCanvas(){const max=1400,s=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(image.naturalWidth*s));c.height=Math.max(1,Math.round(image.naturalHeight*s));c.getContext("2d").drawImage(image,0,0,c.width,c.height);return c}
function readMask(m){return m?{w:m.width,h:m.height,a:new Float32Array(m.getAsFloat32Array())}:null}
function buildForegroundMask(r,hr){const ms=r.confidenceMasks||[];if(ms.length<6)throw Error("Portrait confidence masks are unavailable.");const m=ms.map(readMask),w=m[0].w,h=m[0].h,out=new Float32Array(w*h),ep=+edge.value/100;const hm=hr?.confidenceMasks?.[0]?readMask(hr.confidenceMasks[0]):null;for(let i=0;i<out.length;i++){let v=Math.max(m[1].a[i],m[2].a[i],m[3].a[i],m[4].a[i],m[5].a[i]*lerp(1,1.14,ep));if(hm&&hm.w===w&&hm.h===h)v=Math.max(v,hm.a[i]*lerp(.95,1.1,ep));out[i]=clamp(v)}return{w,h,a:out}}
function maskToCanvas(m){const c=document.createElement("canvas");c.width=m.w;c.height=m.h;const x=c.getContext("2d"),d=x.createImageData(m.w,m.h);for(let i=0;i<m.a.length;i++){const a=Math.round(m.a[i]*255);d.data[i*4]=255;d.data[i*4+1]=255;d.data[i*4+2]=255;d.data[i*4+3]=a}x.putImageData(d,0,0);return c}
function resizeMask(c,w,h){const o=document.createElement("canvas");o.width=w;o.height=h;const x=o.getContext("2d");x.imageSmoothingEnabled=true;x.drawImage(c,0,0,w,h);return o}
function refinedAlpha(c,w,h){const ep=+edge.value/100,b=lerp(2.8,.7,ep),o=document.createElement("canvas");o.width=w;o.height=h;const x=o.getContext("2d");x.filter=`blur(${b}px)`;x.drawImage(c,0,0,w,h);x.filter="none";const d=x.getImageData(0,0,w,h);for(let i=0;i<d.data.length;i+=4){const a=d.data[i+3]/255;d.data[i+3]=Math.round((a>.78?1:a)*255)}x.putImageData(d,0,0);return o}
function blurBackground(src,w,h,blur){const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d"),passes=Math.max(1,Math.ceil(blur/18)),r=Math.min(18,blur/passes);x.filter=`blur(${r}px)`;for(let i=0;i<passes;i++)x.drawImage(src,0,0,w,h);x.filter="none";return c}
function grade(c){const x=c.getContext("2d"),t=preset.value,temp=document.createElement("canvas");temp.width=c.width;temp.height=c.height;const tx=temp.getContext("2d");tx.drawImage(c,0,0);x.filter=t==="natural"?"contrast(1.04) saturate(1.06) brightness(1.015)":t==="studio"?"contrast(1.02) saturate(1.02) brightness(1.05)":t==="warm"?"contrast(1.04) saturate(1.10) sepia(.10) brightness(1.02)":t==="cool"?"contrast(1.05) saturate(1.04) hue-rotate(-5deg) brightness(1.015)":t==="dramatic"?"contrast(1.18) saturate(1.08) brightness(.99)":"grayscale(1) contrast(1.10)";x.clearRect(0,0,c.width,c.height);x.drawImage(temp,0,0);x.filter="none";x.save();if(t==="warm"){x.globalCompositeOperation="soft-light";x.globalAlpha=.07;x.fillStyle="#ff9a55";x.fillRect(0,0,c.width,c.height)}else if(t==="cool"){x.globalCompositeOperation="soft-light";x.globalAlpha=.06;x.fillStyle="#6e9edb";x.fillRect(0,0,c.width,c.height)}x.restore()}
async function render(){if(!working||!multiMask)return;const w=working.width,h=working.height,small=maskToCanvas(multiMask),mask=resizeMask(small,w,h),alpha=refinedAlpha(mask,w,h);if(showMask.checked){pctx.drawImage(working,0,0);const o=document.createElement("canvas");o.width=w;o.height=h;const x=o.getContext("2d");x.fillStyle="#26e6a1";x.globalAlpha=.4;x.fillRect(0,0,w,h);x.globalCompositeOperation="destination-in";x.drawImage(alpha,0,0);pctx.drawImage(o,0,0);finalCanvas=working;return}const d=+depth.value/100,bg=blurBackground(working,w,h,lerp(2,34,d)),out=document.createElement("canvas");out.width=w;out.height=h;const x=out.getContext("2d");x.drawImage(bg,0,0);x.globalCompositeOperation="source-over";x.drawImage(working,0,0);x.globalCompositeOperation="destination-in";x.drawImage(alpha,0,0);x.globalCompositeOperation="destination-over";x.drawImage(bg,0,0);grade(out);finalCanvas=out;pctx.clearRect(0,0,w,h);pctx.drawImage(out,0,0)}
async function run(){if(!image||busy)return;busy=true;processBtn.disabled=true;downloadBtn.disabled=true;setStatus("Analyzing hair, face and accessory edges…");try{working=makeWorkingCanvas();preview.width=working.width;preview.height=working.height;const r=multiSegmenter.segment(working),hr=hairSegmenter.segment(working);multiMask=buildForegroundMask(r,hr);r.close();hr.close();await render();setStatus("Ready — test hair spikes, glasses and objects beside the face.");downloadBtn.disabled=false}catch(e){console.error(e);setStatus("Portrait processing failed: "+e.message)}finally{processBtn.disabled=false;busy=false}}
fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;image=new Image();image.onload=()=>{working=makeWorkingCanvas();preview.width=working.width;preview.height=working.height;pctx.drawImage(working,0,0);processBtn.disabled=!multiSegmenter;setStatus(multiSegmenter?"Photo ready. Apply Portrait.":"Loading portrait model…")};image.src=URL.createObjectURL(f)});processBtn.addEventListener("click",run);[depth,edge,preset].forEach(el=>el.addEventListener("input",async()=>{$("depthValue").textContent=depth.value+"%";const e=+edge.value;$("edgeValue").textContent=e>70?"High":e>40?"Medium":"Low";$("presetValue").textContent=preset.options[preset.selectedIndex].text;if(multiMask)await render()}));showMask.addEventListener("change",()=>multiMask&&render());downloadBtn.addEventListener("click",()=>{if(!finalCanvas)return;const a=document.createElement("a");a.download="portrait-draft.jpg";a.href=finalCanvas.toDataURL("image/jpeg",.94);a.click()});initModels().catch(e=>{console.error(e);setStatus("Model load failed. Refresh and check your connection.")});
